services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    volumes:
      - crawlzilla_es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - crawlzilla_elk

  crawlzilla_logstash:
    container_name: crawlzilla_logstash
    image: docker.elastic.co/logstash/logstash:8.15.3
    volumes:
      - ./logger/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LOGSTASH_PORT: 5228
      LOGSTASH_INDEX: "test-index"
      ELASTIC_HOST: "elasticsearch:9200"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "elastic"
    networks:
      - crawlzilla_elk
    depends_on:
      - elasticsearch

  crawlzilla_kibana:
    image:  docker.elastic.co/kibana/kibana:8.15.3
    container_name: crawlzilla_kibana
    ports:
      - "5601:5601"
    networks:
      - crawlzilla_elk
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "elastic"

networks:
  crawlzilla_elk:
    driver: bridge

volumes:
  crawlzilla_es_data:
    driver: local
